vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        covers:
            uri_prefix: '%upload_directory%'
            upload_destination: '%kernel.project_dir%/public/%upload_directory%'
            namer:  Vich\UploaderBundle\Naming\SmartUniqueNamer